# Generated by Django 5.2.7 on 2025-10-29 13:47

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_options_student_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=users.models.Student.student_photo_path),
        ),
    ]
