# Generated by Django 5.2.7 on 2025-10-30 16:20

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=users.models.CustomUser.user_photo_path),
        ),
    ]
