# Generated by Django 5.2.7 on 2025-10-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_attachment_notice_attachment_name'),
        ('users', '0002_alter_student_options_student_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_classes',
            field=models.ManyToManyField(blank=True, related_name='notices', to='users.class'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
